### PR TITLE
 Make entry a package and not a plugin.

### PR DESCRIPTION
**Pull request by ruudvring**
Since there is no platform specific code, this will work fine without being a plugin.

### CODE REVIEW

**Comment by MickaelHrndz** [comment]
Thank you for this. I overlooked that part, but it felt weird having these platform-specific folders. However, I don't think removing them in the example project is correct, I need those.

**Comment by ruudvring** [comment]
For the example folder it is ok to run `flutter create .` (note the dot), this will create all platform folders,
and then run the sample with `flutter run` 
A menu will appear where you can choose the platform (device) to run on.

**Comment by MickaelHrndz** [comment]
Yes I know that thank you, I already commited the files. I'm ok with the PR state right now, I'll merge if you are as well.

**Comment by ruudvring** [comment]
Fine by me, and thank you for the nice package.

**Pull request merged**
